version: '3.9'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: vinicius
      POSTGRES_DB: planet
    ports:
      - "5432:5432"
    networks:
      - network1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - network1

  rabbit_mq:
    image: rabbitmq
    container_name: rabbit_mq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: vinicius
      RABBITMQ_DEFAULT_PASS: vinicius
    networks:
      - network1

  reservation-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: reservation-service_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/planet
      SPRING_DATASOURCE_USERNAME: vinicius
      SPRING_DATASOURCE_PASSWORD: vinicius
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8080"
    command: ["java", "-jar", "/app/reservation-service.jar"]
    depends_on:
      - postgres
      - redis
      - rabbit_mq
    networks:
      - network1

  notification-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: notification-service_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/planet
      SPRING_DATASOURCE_USERNAME: vinicius
      SPRING_DATASOURCE_PASSWORD: vinicius
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    command: ["java", "-jar", "/app/notification-service.jar"]
    depends_on:
      - postgres
      - redis
      - rabbit_mq
    networks:
      - network1

volumes:
  postgres_data:

networks:
  network1:
    driver: bridge